apiVersion: v2
appVersion: "5.2-22.04_beta"

# Please make sure your name DOES NOT end in "app" or "-app".
name: squid-proxy

# Please describe what the app provides in a sentence or two.
description: squid proxy for giantswarm internal use

home: https://github.com/giantswarm/squid-proxy-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg

version: 0.6.5-dev
annotations:
  io.giantswarm.application.team: phoenix
